-- =============================================================
-- My Litters — Postgres schema (reference DDL)
-- Product model: Hybrid (monthly plan tier + per-tap BNPL transactions)
--
-- Notes
--   - This file is a *design reference*. The actual migrations are
--     generated by Prisma from prisma/schema.prisma (task #3).
--   - All money columns use NUMERIC(12, 3) to allow fractional liters
--     and SAR halalah precision without floating-point error.
--   - All timestamps are TIMESTAMPTZ (UTC); the app converts to local
--     time on display.
--   - UUIDs are used for primary keys to keep the API surface stable
--     and to avoid leaking row counts.
-- =============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "citext";     -- case-insensitive email column

-- -------------------------------------------------------------
-- Enumerated types
-- -------------------------------------------------------------
CREATE TYPE user_role        AS ENUM ('customer', 'staff', 'admin');
CREATE TYPE fuel_type        AS ENUM ('p91', 'p95', 'diesel');
CREATE TYPE card_status      AS ENUM ('active', 'blocked', 'lost');
CREATE TYPE sub_status       AS ENUM ('active', 'paused', 'canceled');
CREATE TYPE txn_status       AS ENUM ('approved', 'declined', 'voided');
CREATE TYPE invoice_status   AS ENUM ('open', 'due', 'paid', 'overdue');
CREATE TYPE payment_method   AS ENUM ('card', 'bank', 'cash', 'wallet');
CREATE TYPE payment_status   AS ENUM ('pending', 'completed', 'failed', 'refunded');

-- -------------------------------------------------------------
-- users — customers, staff, admins
-- -------------------------------------------------------------
CREATE TABLE users (
    id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email          CITEXT       UNIQUE NOT NULL,
    phone          TEXT         UNIQUE,
    password_hash  TEXT         NOT NULL,
    full_name      TEXT         NOT NULL,
    national_id    TEXT         UNIQUE,           -- KYC; nullable for MVP
    role           user_role    NOT NULL DEFAULT 'customer',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------
-- vehicles — owned by a user, fuel preference is per-vehicle
-- -------------------------------------------------------------
CREATE TABLE vehicles (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plate_number TEXT        NOT NULL,
    make         TEXT,
    model        TEXT,
    year         INT,
    fuel_type    fuel_type   NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, plate_number)
);
CREATE INDEX vehicles_user_idx ON vehicles(user_id);

-- -------------------------------------------------------------
-- plans — catalog of subscription tiers (admin-managed)
-- A plan defines: which fuel type, monthly liter cap, rate, fee.
-- -------------------------------------------------------------
CREATE TABLE plans (
    id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name                  TEXT         NOT NULL,           -- "Basic 95", "Plus 95", ...
    fuel_type             fuel_type    NOT NULL,
    monthly_liters_limit  INT          NOT NULL,           -- soft cap; declines above this
    price_per_liter       NUMERIC(12,3) NOT NULL,          -- snapshot at txn time
    monthly_fee           NUMERIC(12,3) NOT NULL DEFAULT 0,
    is_active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------
-- subscriptions — a user's enrollment in a plan
-- One *active* subscription per user (enforced via partial index).
-- -------------------------------------------------------------
CREATE TABLE subscriptions (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id       UUID         NOT NULL REFERENCES plans(id),
    status        sub_status   NOT NULL DEFAULT 'active',
    credit_limit  NUMERIC(12,3) NOT NULL,                  -- max BNPL exposure
    billing_day   SMALLINT     NOT NULL DEFAULT 1
                  CHECK (billing_day BETWEEN 1 AND 28),
    started_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ends_at       TIMESTAMPTZ
);
CREATE UNIQUE INDEX one_active_sub_per_user
    ON subscriptions(user_id) WHERE status = 'active';
CREATE INDEX subscriptions_user_idx ON subscriptions(user_id);

-- -------------------------------------------------------------
-- cards — physical NFC cards linked to a user
-- One user may hold multiple cards (e.g., one per vehicle).
-- card_uid is the NFC tag's hardware identifier (hex string).
-- -------------------------------------------------------------
CREATE TABLE cards (
    id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_uid   TEXT         UNIQUE NOT NULL,
    label      TEXT,                                        -- e.g. "Sedan card"
    status     card_status  NOT NULL DEFAULT 'active',
    linked_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX cards_user_idx ON cards(user_id);

-- -------------------------------------------------------------
-- stations — fuel stations (seeded for MVP demo)
-- -------------------------------------------------------------
CREATE TABLE stations (
    id        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name      TEXT         NOT NULL,
    city      TEXT,
    lat       NUMERIC(9,6),
    lng       NUMERIC(9,6),
    is_active BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------
-- invoices — monthly billing bundles for a subscription
-- Created by a scheduled job at end of each billing period.
-- -------------------------------------------------------------
CREATE TABLE invoices (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID            NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subscription_id UUID            NOT NULL REFERENCES subscriptions(id),
    period_start    DATE            NOT NULL,
    period_end      DATE            NOT NULL,
    subtotal        NUMERIC(12,3)   NOT NULL DEFAULT 0,    -- sum(transactions.total_amount)
    monthly_fee     NUMERIC(12,3)   NOT NULL DEFAULT 0,
    total           NUMERIC(12,3)   NOT NULL DEFAULT 0,    -- subtotal + monthly_fee
    status          invoice_status  NOT NULL DEFAULT 'open',
    due_date        DATE            NOT NULL,
    paid_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    UNIQUE (subscription_id, period_start)
);
CREATE INDEX invoices_user_idx   ON invoices(user_id);
CREATE INDEX invoices_status_idx ON invoices(status);

-- -------------------------------------------------------------
-- transactions — every NFC tap = one row
-- Authorized against active subscription's remaining credit.
-- Linked to an invoice once the period closes.
-- -------------------------------------------------------------
CREATE TABLE transactions (
    id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_id          UUID          NOT NULL REFERENCES cards(id),
    subscription_id  UUID          NOT NULL REFERENCES subscriptions(id),
    station_id       UUID          REFERENCES stations(id),
    vehicle_id       UUID          REFERENCES vehicles(id),
    liters           NUMERIC(8,3)  NOT NULL CHECK (liters > 0),
    price_per_liter  NUMERIC(12,3) NOT NULL,                -- snapshot of plan rate
    total_amount     NUMERIC(12,3) NOT NULL,                -- liters * price_per_liter
    fuel_type        fuel_type     NOT NULL,
    status           txn_status    NOT NULL DEFAULT 'approved',
    decline_reason   TEXT,
    invoice_id       UUID          REFERENCES invoices(id), -- NULL until period closes
    tapped_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX txn_user_tapped_idx ON transactions(user_id, tapped_at DESC);
CREATE INDEX txn_subscription_idx ON transactions(subscription_id);
CREATE INDEX txn_invoice_idx     ON transactions(invoice_id);
CREATE INDEX txn_card_idx        ON transactions(card_id);

-- -------------------------------------------------------------
-- payments — repayments against invoices
-- An invoice can have multiple payments (partial settlement).
-- -------------------------------------------------------------
CREATE TABLE payments (
    id          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id  UUID            NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    user_id     UUID            NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount      NUMERIC(12,3)   NOT NULL CHECK (amount > 0),
    method      payment_method  NOT NULL,
    reference   TEXT,                                       -- gateway txn ref
    status      payment_status  NOT NULL DEFAULT 'pending',
    paid_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now()
);
CREATE INDEX payments_invoice_idx ON payments(invoice_id);
CREATE INDEX payments_user_idx    ON payments(user_id);

-- =============================================================
-- Convenience view: a user's current available credit
-- =============================================================
CREATE OR REPLACE VIEW v_user_available_credit AS
SELECT
    s.user_id,
    s.id          AS subscription_id,
    s.credit_limit,
    COALESCE(SUM(t.total_amount) FILTER (
        WHERE t.status = 'approved' AND t.invoice_id IS NULL
    ), 0)         AS unbilled_balance,
    s.credit_limit - COALESCE(SUM(t.total_amount) FILTER (
        WHERE t.status = 'approved' AND t.invoice_id IS NULL
    ), 0)         AS available_credit
FROM subscriptions s
LEFT JOIN transactions t ON t.subscription_id = s.id
WHERE s.status = 'active'
GROUP BY s.id;
